export const VIETNAM_PROVINCES = [
  'An Giang',
  'Bà Rịa – Vũng Tàu',
  'Bắc Giang',
  'Bắc Kạn',
  'Bạc Liêu',
  'Bắc Ninh',
  'Bến Tre',
  'Bình Định',
  'Bình Dương',
  'Bình Phước',
  'Bình Thuận',
  'Cà Mau',
  'Cần Thơ',
  'Cao Bằng',
  'Đà Nẵng',
  'Đắk Lắk',
  'Đắk Nông',
  'Điện Biên',
  'Đồng Nai',
  'Đồng Tháp',
  'Gia Lai',
  'Hà Giang',
  'Hà Nam',
  'Hà Nội',
  'Hà Tĩnh',
  'Hải Dương',
  'Hải Phòng',
  'Hậu Giang',
  'Hòa Bình',
  'Hưng Yên',
  'Khánh Hòa',
  'Kiên Giang',
  'Kon Tum',
  'Lai Châu',
  'Lâm Đồng',
  'Lạng Sơn',
  'Lào Cai',
  'Long An',
  'Nam Định',
  'Nghệ An',
  'Ninh Bình',
  'Ninh Thuận',
  'Phú Thọ',
  'Phú Yên',
  'Quảng Bình',
  'Quảng Nam',
  'Quảng Ngãi',
  'Quảng Ninh',
  'Quảng Trị',
  'Sóc Trăng',
  'Sơn La',
  'Tây Ninh',
  'Thái Bình',
  'Thái Nguyên',
  'Thanh Hóa',
  'Thừa Thiên Huế',
  'Tiền Giang',
  'TP Hồ Chí Minh',
  'Trà Vinh',
  'Tuyên Quang',
  'Vĩnh Long',
  'Vĩnh Phúc',
  'Yên Bái',
] as const;

export interface DegreeTypeOption {
  label: string;
  category: 'Văn bằng' | 'Chứng chỉ';
}

export const DEGREE_TYPES: DegreeTypeOption[] = [
  // Nhóm Văn bằng
  { label: "Cử nhân (Bachelor's Degree)", category: 'Văn bằng' },
  { label: "Kỹ sư (Engineer's Degree)", category: 'Văn bằng' },
  { label: "Kiến trúc sư (Architect's Degree)", category: 'Văn bằng' },
  { label: "Bác sĩ thú y (Doctor of Veterinary Medicine)", category: 'Văn bằng' },
  { label: "Thạc sĩ (Master's Degree)", category: 'Văn bằng' },
  { label: "Tiến sĩ (Doctorate/Ph.D)", category: 'Văn bằng' },

  // Nhóm Chứng chỉ
  { label: 'Chứng chỉ Ứng dụng Công nghệ Thông tin (Cơ bản / Nâng cao)', category: 'Chứng chỉ' },
  { label: 'Chứng chỉ Năng lực Ngoại ngữ 6 bậc dùng cho Việt Nam (VSTEP)', category: 'Chứng chỉ' },
  { label: 'Chứng chỉ Tiếng Việt cho người nước ngoài', category: 'Chứng chỉ' },
  { label: 'Chứng chỉ Bồi dưỡng Nghiệp vụ Sư phạm', category: 'Chứng chỉ' },
  { label: 'Chứng chỉ Bồi dưỡng theo tiêu chuẩn chức danh nghề nghiệp', category: 'Chứng chỉ' },
  { label: 'Chứng chỉ Quản lý nhà nước / Quản lý giáo dục', category: 'Chứng chỉ' },
  { label: 'Chứng chỉ Kế toán trưởng, Kế toán thực hành, Khai báo thuế', category: 'Chứng chỉ' },
  { label: 'Chứng chỉ CNTT ngắn hạn (Aptech, Thiết kế đồ họa, Quản trị mạng, Lập trình Web)', category: 'Chứng chỉ' },
];

export const MODE_OF_STUDY_OPTIONS = [
  'Chính quy',
  'Vừa học vừa làm',
  'Đào tạo từ xa',
] as const;

